# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180210_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.CharField(max_length=140),
        ),
    ]
